import json
import requests
import pandas as pd
from sqlalchemy import create_engine
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from datetime import datetime, timedelta
import http.client
import sqlite3
from app import *
from pprint import pprint

# url_datagouv = ("https://www.data.gouv.fr/fr/datasets/r/759b5ec2-a585-477a-9c62-7f74a7bdec3d")
# url_ameli = "https://datavaccin-covid.ameli.fr/api/v2/catalog/datasets/donnees-de-vaccination-par-commune/exports/json?limit=-1&offset=0&timezone=UTC"
covid_json = "data/datacovid.json"
covid_json = "data/datacovid_ameli.json"


def call_api_covid(date):
    # Initialisation des diff√©rents √©l√©ments qui vont constituer notre URL/requ√™te
    AMELI_ENDPOINT = "https://datavaccin-covid.ameli.fr/api/records/1.0/search/?dataset=donnees-de-vaccination-par-commune&q="  # nom du dataset √† interroger
    params = "&rows=10000&refine.date={}".format(date)
    AMELI_ENDPOINT = AMELI_ENDPOINT + params
    AMELI_API_KEY = "e9a377dea52545f74ec78efe79513f8466bee6be8fead520c362a5ad"  # api_key pour se connecter √† l'API
    headers = {"appid": AMELI_API_KEY}

    response = requests.get(AMELI_ENDPOINT, params=headers)
    response.raise_for_status()
    return response.json()


# Mise √† jour des donn√©es depuis data gouv
def update_data_covid():
    # TODO : appliquer la requ√™te avec SQLAlchemy pour extraire la derni√®re date de la BDD pour ensuite t√©l√©charger 
    """ pas r√©ussi √† formuler la requ√™te dans l'URL avec ">" : proposition : r√©cup√©rer chaque jour les donn√©es avec comme param√®tre date=today ou date=yesterday (car on ne sait pas √† quelle heure datagouv met √† jour ses donn√©es ?) """
    #  les donn√©es qui ont √©t√© rajout√©es dans l'API Ameli 
    #date_derniere_donnees = "SELECT MAX(date) FROM DATA_COVID"  # chercher la derni√®re date dans la base de donn√©e
    json_covid = call_api_covid(datetime.today().strftime('%Y-%m-%d'))  # appel de la fonction d'interrogation de l'API
    # üêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩ
    # Test manuel (√©chec car Key error --> voir grouins ci-dessous)
    json_covid = call_api_covid("2022-03-06")
    try:
        update_db(json_covid)  # mise √† jour de la BD avec le JSON en retour
    except Exception as e:
        print(e)
        pass


def update_db(data):
    """ üêΩüêΩüêΩ m√©thode avec create_engine : √©chec 
    /!\ car CONFLIT SQLAlchemy / Pandas (m√™me avec la version 1.4.32 de sqlalchemy install√©e)
    # Create A DataFrame From the JSON Data
    df = pd.DataFrame(data)
    #Conversion en une db
    engine = create_engine("sqlite:///DataViewer.db")
    df.to_sql("test_table_covid",engine)"""
    # ETAPE SUIVANTE = AJOUT DES NOUVELLES DONNEES DANS LA DB
    # en proc√©dant de cette mani√®re, n'influe pas sur les ajouts/suppressions/modifications des users
    # conn = sqlite3.connect(db)
    # c = conn.cursor()
    # üêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩüêΩ
    # TODO parcours du json ---> OK
    #      g√©rer les KeyError ou se contenter de la synchronisation v2 
    #      ---> c'est NUL quand on envoie la requ√™te avec l'API √ßa ne renvoie pas les champs qui ont pour valeur null
    for dic1 in data["records"]:
        dic = dic1["fields"]
        date_reference = dic["date_reference"]
        semaine_injection = dic["semaine_injection"]
        commune_residence = dic["commune_residence"]
        libelle_commune = dic["libelle_commune"]
        population_carto = dic["population_carto"]
        classe_age = dic["classe_age"]
        libelle_classe_age = dic["libelle_classe_age"]
        effectif_1_inj = dic["effectif_1_inj"]
        effectif_termine = dic["effectif_termine"]
        effectif_cumu_1_inj = dic["effectif_cumu_1_inj"]
        effectif_cumu_termine = dic["effectif_cumu_termine"]
        taux_1_inj = dic["taux_1_inj"]
        taux_termine = dic["taux_termine"]
        taux_cumu_1_inj = dic["taux_cumu_1_inj"]
        taux_cumu_termine = dic["taux_cumu_termine"]
        date = dic["date"]

        data = DATA_COVID(date_reference=date_reference,
                          semaine_injection=semaine_injection,
                          commune_residence=commune_residence,
                          libelle_commune=libelle_commune, population_carto=population_carto, classe_age=classe_age,
                          libelle_classe_age=libelle_classe_age, effectif_1_inj=effectif_1_inj,
                          effectif_termine=effectif_termine,
                          effectif_cumu_1_inj=effectif_cumu_1_inj, effectif_cumu_termine=effectif_cumu_termine,
                          taux_1_inj=taux_1_inj, taux_termine=taux_termine, taux_cumu_1_inj=taux_cumu_1_inj,
                          taux_cumu_termine=taux_cumu_termine,
                          date=date)

    db.session.add(data)
    db.session.commit()


# SYNCHRONISATION
# Cr√©er un objet Scheduler pour une t√¢che programm√©e
# scheduler = BackgroundScheduler()
# Ajouter une t√¢che programm√©e √† l'ordonnanceur (mise √† jour des donn√©es depuis datagouv + mise √† jour de base de donn√©es)
# D√©finition de l'intervalle : tous les jours
# scheduler.add_job(update_data_covid(url_ameli, covid_json), 'interval', days=1)
#  D√©marrer le travail du planificateur de t√¢ches programm√© 
# scheduler.start()
pprint(call_api_covid("2022-03-06")["records"])
update_data_covid()

""" 
/!\ POUR L'INSTANT : scheduler renvoie une erreur
Mais les t√¢ches marchent, et la db se met √† jour
(YOUPI ! VICTOIRE !!!!)
"""
# new_data = update_data_covid(url_ameli, covid_json)
# update_db(new_data)
